---
AllCops:
  NewCops: enable
  TargetRubyVersion: 2.5
Naming/AccessorMethodName:
  Enabled: false
Layout/LineLength:
  Max: 100
Style/GlobalVars:
  AllowedVariables:
    - $env
    - $parameters
    - $toggle
Style/Documentation:
  Enabled: false
